### ISSUE TITLE
How to handle iframe pages ?

### ISSUE THREAD

**Issue by renqabs** [ultrafunkamsterdam/nodriver#1]
For example, the following link: https://www.bing.com/turing/captcha/challenge

**Comment by ultrafunkamsterdam** [comment]
please not this is not yet usable. Still building the repo. 
Maybe this will do:

![image](https://github.com/ultrafunkamsterdam/nodriver/assets/21027969/7a44bae1-bb96-4766-99e8-ee71a1f2ac30)
