### ISSUE TITLE
Can Handle Alert?

### ISSUE THREAD

**Issue by PacharaXx** [ultrafunkamsterdam/nodriver#6]
![image](https://github.com/user-attachments/assets/6910ddff-9f13-4a9f-b6d9-54aa8399aa86)
can nodriver handle alert?

**Comment by KenyOnFire** [comment]
Check this https://ultrafunkamsterdam.github.io/nodriver/nodriver/cdp/page.html#nodriver.cdp.page.DialogType

**Comment by devblack** [comment]
>  can nodriver handle alert?
Close this pls.
